### ISSUE TITLE
[Moderator] Missing !tempmute, !tempban

### ISSUE THREAD

**Issue by kpeckett** [Mee6/Mee6-documentation#27]

**Comment by Doc1337** [comment]
but who needs temp ban when you can ban forever, @SilBoydens knows what i mean

**Comment by SilBoydens** [comment]
@Doc1337 shut up 😡 
@kpeckett these dogs are for V1, we are still working on the new docs

**Comment by Doc1337** [comment]
@SilBoydens lol you banned me for nothing
![image](https://user-images.githubusercontent.com/15276167/37852186-f612b524-2ee1-11e8-909a-4925b25cf83d.png)

**Comment by SilBoydens** [comment]
And unbanned you..... Twice

**Comment by Doc1337** [comment]
@SilBoydens still i dont deserve perma for saying your location when you make it obvious at your paypal.me link

**Comment by Doc1337** [comment]
you can take the money i send you for medications
