### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by AndrewYoungs** [Mee6/Mee6-documentation#29]
Would it be possible to add a {0} argument that takes in all arguments following a command as a string?  
  
e.g. !suggest Hi, this server is cool but can you add a music channel?  
  
!suggest then fires off "Hi, this server is cool but can you add a music channel?" as {0} to a channel or some such.  
  
Trying to set up a suggestions inbox for a large collegiate gaming community on Discord.

**Comment by SilBoydens** [comment]
is on idea's list, but in a different form of {1...} or simular (also supporting {1...5} for the first 5, etc....)

**Comment by AndrewYoungs** [comment]
Oh cool, do you need any help implementing this? :) I work with Python and this would be really useful to our community.

**Comment by SilBoydens** [comment]
the new Mee6 bot is not open source and i don't think we accept code contributions atm, try asking Cookie#1337 in the Mee6 server if you really want to help

**Comment by AndrewYoungs** [comment]
Thanks Sil! :D I guess a prudent question to ask would be, is this being worked on at the moment or is it only in the planning stages? We want to have a suggestions feature implemented (without having to put together a whole bot for our specific community needs) before the start of the next academic year.

**Comment by IsNotADeveloper** [comment]
Not really in the planning stages, we've paused active feature planning and are focusing on fixing some internal things before proceeding with features.

Please visit discord.gg/mee6 for support, suggestions, or to contact our developer staff.

**Comment by AndrewYoungs** [comment]
Yup, thanks for the reply. I'll go ahead and close this off now.
