### ISSUE TITLE
Unintended response

### ISSUE THREAD

**Issue by playlix42** [Mee6/Mee6-documentation#46]
As a member of a Server using mee6 I got following response by customizing a rank card: `{"error":{"message":"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."},"status_code":500}`.

What did I exactly?
I got a link for customizing the rank card and after connecting I had to log in. I was redirected to discord, logged in and has been redirected back to https://mee6.xyz/api/discord-callback?code=xxxxxxxxxxxx&state=yyyyyyyyyyyy. During the last reconnection my network failed and the site didn't load. After reconnecting to the Internet and reloading the page I got the clear Server response specified above.
I think IT isn't intended that this occures.

Regards, playlix42

**Comment by SilBoydens** [comment]
hi, the "discord-callback" route is part of the login procedure. for security reasons, the whole login procedure has to be done done in 1 take.

pls try again starting at https://mee6.xyz
