### ISSUE TITLE
Birthday function (idea)

### ISSUE THREAD

**Issue by rukoe** [Mee6/Mee6-documentation#48]
It would be nice if it's possible to bypass the Limit of only 10 B-Days shown via the !next-birthdays command.
so a command like !all-birthdays would be handy, or an option to chagde the value of the shown B-Days.
Thanks a lot.
(hope this is the right place to post this couse I'm still pretty net to GitHub)

**Comment by SilBoydens** [comment]
suggestions for the bot should be in the bot support server
